### ISSUE TITLE
Building MCUBoot for Zephyr fails on multiple ARM boards

### ISSUE THREAD

**Issue by mnkp** [JuulLabs-OSS/mcuboot#699]
Building latest version of MCUBoot for Zephyr, e.g.
```
west build -b stm32f0_disco bootloader/mcuboot/boot/zephyr/
```
is causing compile time error.
```
bootloader/mcuboot/boot/zephyr/arm_cleanup.c:15:34: error: 'NVIC' undeclared (first use in this function)
   15 |  for (u8_t i = 0; i < ARRAY_SIZE(NVIC->ICER); i++) {
```
The issue can be seen on multiple ARM boards and was introduced by #683.

The `arm_cleanup.c` source file relies on CMSIS, however it includes only `zephyr.h` which is used to provide kernel API, not necessarily give access to CPU internals.

It seems like at present it is possible to compile MCUBoot only on those ARM boards which enable MPU since cmsis becomes available through some implicit header file dependencies.
